name: "Compliance"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: write

jobs:
  compliance:
    uses: lloydlobo/homely-recipes/.github/workflows/compliance.yml@main
